# Configuracion de los mensajes de JaCaMo.
handlers = java.util.logging.ConsoleHandler

# Nivel general: SEVERE (errores graves), WARNING (avisos), INFO o FINE (depuracion).
.level = INFO

# Presentacion de los mensajes de los agentes.
jason.runtime.MASConsoleLogHandler.level = ALL
jason.runtime.MASConsoleLogHandler.formatter = jason.runtime.MASConsoleLogFormatter
jason.runtime.MASConsoleLogHandler.tabbed = true
jason.runtime.MASConsoleLogHandler.colors = false

# Configuracion de los archivos de registro si se activa FileHandler.
java.util.logging.FileHandler.pattern = log/mas-%g.log
java.util.logging.FileHandler.limit = 500000
java.util.logging.FileHandler.count = 10
java.util.logging.FileHandler.formatter = jason.runtime.MASConsoleLogFormatter

# Mensajes mostrados en la consola.
java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.level=OFF
javax.level=OFF
sun.level=OFF
jade.level=OFF
